name: Install Docker and SonarQube

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt install containerd
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Install SonarQube
        run: |
          sudo docker run -d --name sonarqube -p 9000:9000 -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true sonarqube:latest
          # Wait for SonarQube to start running
          sleep 30
          curl -u admin:admin http://localhost:9000/api/system/status
      - name: SSH into the GitHub runner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ runner.ip }}
          username: ${{ runner.os == 'Linux' && 'ubuntu' || 'runneradmin' }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ runner.port }}
          script: |
            ssh -L 9000:localhost:9000 -N ${{ runner.os == 'Linux' && 'ubuntu' || 'runneradmin' }}@${{ runner.ip }}      
